name: When a push occurs in master branch, a private msg is sent to the whatsapp.
on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install twilio
        run: pip install twilio
      - name: run code
        run: python main.py
        env:
          account_sid: ${{ secrets.account_sid }}
          auth_token: ${{ secrets.auth_token }}
          whatsapp_no: ${{ secrets.whatsapp_no }}
